In [2]:
import pandas as pd

In [23]:
url = "https://catalog.ourworldindata.org/garden/covid/latest/compact/compact.csv"
df = pd.read_csv(url)

In [24]:

print(df['country'].unique())
print(len(df['country'].unique()))

['Afghanistan' 'Africa' 'Albania' 'Algeria' 'American Samoa' 'Andorra'
 'Angola' 'Anguilla' 'Antigua and Barbuda' 'Argentina' 'Armenia' 'Aruba'
 'Asia' 'Asia excl. China' 'Australia' 'Austria' 'Azerbaijan' 'Bahamas'
 'Bahrain' 'Bangladesh' 'Barbados' 'Belarus' 'Belgium' 'Belize' 'Benin'
 'Bermuda' 'Bhutan' 'Bolivia' 'Bonaire Sint Eustatius and Saba'
 'Bosnia and Herzegovina' 'Botswana' 'Brazil' 'British Virgin Islands'
 'Brunei' 'Bulgaria' 'Burkina Faso' 'Burundi' 'Cambodia' 'Cameroon'
 'Canada' 'Cape Verde' 'Cayman Islands' 'Central African Republic' 'Chad'
 'Chile' 'China' 'Colombia' 'Comoros' 'Congo' 'Cook Islands' 'Costa Rica'
 "Cote d'Ivoire" 'Croatia' 'Cuba' 'Curacao' 'Cyprus' 'Czechia'
 'Democratic Republic of Congo' 'Denmark' 'Djibouti' 'Dominica'
 'Dominican Republic' 'East Timor' 'Ecuador' 'Egypt' 'El Salvador'
 'England' 'England & Wales' 'Equatorial Guinea' 'Eritrea' 'Estonia'
 'Eswatini' 'Ethiopia' 'Europe' 'European Union (27)' 'Falkland Islands'
 'Faroe Islands' 'Fiji' 'Finland' 'France' 'French Guiana'
 'French Polynesia' 'Gabon' 'Gambia' 'Georgia' 'Germany' 'Ghana'
 'Gibraltar' 'Greece' 'Greenland' 'Grenada' 'Guadeloupe' 'Guam'
 'Guatemala' 'Guernsey' 'Guinea' 'Guinea-Bissau' 'Guyana' 'Haiti'
 'High-income countries' 'Honduras' 'Hong Kong' 'Hungary' 'Iceland'
 'India' 'Indonesia' 'Iran' 'Iraq' 'Ireland' 'Isle of Man' 'Israel'
 'Italy' 'Jamaica' 'Japan' 'Jersey' 'Jordan' 'Kazakhstan' 'Kenya'
 'Kiribati' 'Kosovo' 'Kuwait' 'Kyrgyzstan' 'Laos' 'Latvia' 'Lebanon'
 'Lesotho' 'Liberia' 'Libya' 'Liechtenstein' 'Lithuania'
 'Low-income countries' 'Lower-middle-income countries' 'Luxembourg'
 'Macao' 'Madagascar' 'Malawi' 'Malaysia' 'Maldives' 'Mali' 'Malta'
 'Marshall Islands' 'Martinique' 'Mauritania' 'Mauritius' 'Mayotte'
 'Mexico' 'Micronesia (country)' 'Moldova' 'Monaco' 'Mongolia'
 'Montenegro' 'Montserrat' 'Morocco' 'Mozambique' 'Myanmar' 'Namibia'
 'Nauru' 'Nepal' 'Netherlands' 'New Caledonia' 'New Zealand' 'Nicaragua'
 'Niger' 'Nigeria' 'Niue' 'North America' 'North Korea' 'North Macedonia'
 'Northern Ireland' 'Northern Mariana Islands' 'Norway' 'Oceania' 'Oman'
 'Pakistan' 'Palau' 'Palestine' 'Panama' 'Papua New Guinea' 'Paraguay'
 'Peru' 'Philippines' 'Pitcairn' 'Poland' 'Portugal' 'Puerto Rico' 'Qatar'
 'Reunion' 'Romania' 'Russia' 'Rwanda' 'Saint Barthelemy' 'Saint Helena'
 'Saint Kitts and Nevis' 'Saint Lucia' 'Saint Martin (French part)'
 'Saint Pierre and Miquelon' 'Saint Vincent and the Grenadines' 'Samoa'
 'San Marino' 'Sao Tome and Principe' 'Saudi Arabia' 'Scotland' 'Senegal'
 'Serbia' 'Seychelles' 'Sierra Leone' 'Singapore'
 'Sint Maarten (Dutch part)' 'Slovakia' 'Slovenia' 'Solomon Islands'
 'Somalia' 'South Africa' 'South America' 'South Korea' 'South Sudan'
 'Spain' 'Sri Lanka' 'Sudan' 'Summer Olympics 2020' 'Suriname' 'Sweden'
 'Switzerland' 'Syria' 'Taiwan' 'Tajikistan' 'Tanzania' 'Thailand' 'Togo'
 'Tokelau' 'Tonga' 'Transnistria' 'Trinidad and Tobago' 'Tunisia' 'Turkey'
 'Turkmenistan' 'Turks and Caicos Islands' 'Tuvalu' 'Uganda' 'Ukraine'
 'United Arab Emirates' 'United Kingdom' 'United States'
 'United States Virgin Islands' 'Upper-middle-income countries' 'Uruguay'
 'Uzbekistan' 'Vanuatu' 'Vatican' 'Venezuela' 'Vietnam' 'Wales'
 'Wallis and Futuna' 'Western Sahara' 'Winter Olympics 2022' 'World'
 'World excl. China' 'World excl. China and South Korea'
 'World excl. China, South Korea, Japan and Singapore' 'Yemen' 'Zambia'
 'Zimbabwe']
262

In [12]:
print(df.head())

       country        date  total_cases  new_cases  new_cases_smoothed  \
0  Afghanistan  2020-01-01          NaN        NaN                 NaN
1  Afghanistan  2020-01-02          NaN        NaN                 NaN
2  Afghanistan  2020-01-03          NaN        NaN                 NaN
3  Afghanistan  2020-01-04          0.0        0.0                 NaN
4  Afghanistan  2020-01-05          0.0        0.0                 NaN

   total_cases_per_million  new_cases_per_million  \
0                      NaN                    NaN
1                      NaN                    NaN
2                      NaN                    NaN
3                      0.0                    0.0
4                      0.0                    0.0

   new_cases_smoothed_per_million  total_deaths  new_deaths  ...  population  \
0                             NaN           NaN         NaN  ...  40578846.0
1                             NaN           NaN         NaN  ...  40578846.0
2                             NaN           NaN         NaN  ...  40578846.0
3                             NaN           0.0         0.0  ...  40578846.0
4                             NaN           0.0         0.0  ...  40578846.0

   population_density  median_age  life_expectancy  gdp_per_capita  \
0           62.215546      16.752              NaN       1516.2733
1           62.215546      16.752              NaN       1516.2733
2           62.215546      16.752              NaN       1516.2733
3           62.215546      16.752              NaN       1516.2733
4           62.215546      16.752              NaN       1516.2733

   extreme_poverty  diabetes_prevalence  handwashing_facilities  \
0              NaN                 10.9               48.214695
1              NaN                 10.9               48.214695
2              NaN                 10.9               48.214695
3              NaN                 10.9               48.214695
4              NaN                 10.9               48.214695

   hospital_beds_per_thousand  human_development_index
0                        0.39                    0.462
1                        0.39                    0.462
2                        0.39                    0.462
3                        0.39                    0.462
4                        0.39                    0.462

[5 rows x 61 columns]

In [34]:
# Lista dos pa√≠ses
countries = ['Afghanistan', 'Africa', 'Albania', 'Algeria', 'American Samoa', 'Andorra', 'Angola', 'Anguilla', 
             'Antigua and Barbuda', 'Argentina', 'Armenia', 'Aruba', 'Asia', 'Asia excl. China', 'Australia', 
             'Austria', 'Azerbaijan', 'Bahamas', 'Bahrain', 'Bangladesh', 'Barbados', 'Belarus', 'Belgium', 
             'Belize', 'Benin', 'Bermuda', 'Bhutan', 'Bolivia', 'Bonaire Sint Eustatius and Saba', 
             'Bosnia and Herzegovina', 'Botswana', 'Brazil', 'British Virgin Islands', 'Brunei', 'Bulgaria', 
             'Burkina Faso', 'Burundi', 'Cambodia', 'Cameroon', 'Canada', 'Cape Verde', 'Cayman Islands', 
             'Central African Republic', 'Chad', 'Chile', 'China', 'Colombia', 'Comoros', 'Congo', 'Cook Islands', 
             'Costa Rica', "Cote d'Ivoire", 'Croatia', 'Cuba', 'Curacao', 'Cyprus', 'Czechia', 'Democratic Republic of Congo', 
             'Denmark', 'Djibouti', 'Dominica', 'Dominican Republic', 'East Timor', 'Ecuador', 'Egypt', 'El Salvador', 
             'England', 'England & Wales', 'Equatorial Guinea', 'Eritrea', 'Estonia', 'Eswatini', 'Ethiopia', 'Europe', 
             'European Union (27)', 'Falkland Islands', 'Faroe Islands', 'Fiji', 'Finland', 'France', 'French Guiana', 
             'French Polynesia', 'Gabon', 'Gambia', 'Georgia', 'Germany', 'Ghana', 'Gibraltar', 'Greece', 'Greenland', 
             'Grenada', 'Guadeloupe', 'Guam', 'Guatemala', 'Guernsey', 'Guinea', 'Guinea-Bissau', 'Guyana', 'Haiti', 
             'High-income countries', 'Honduras', 'Hong Kong', 'Hungary', 'Iceland', 'India', 'Indonesia', 'Iran', 'Iraq', 
             'Ireland', 'Isle of Man', 'Israel', 'Italy', 'Jamaica', 'Japan', 'Jersey', 'Jordan', 'Kazakhstan', 'Kenya', 
             'Kiribati', 'Kosovo', 'Kuwait', 'Kyrgyzstan', 'Laos', 'Latvia', 'Lebanon', 'Lesotho', 'Liberia', 'Libya', 
             'Liechtenstein', 'Lithuania', 'Low-income countries', 'Lower-middle-income countries', 'Luxembourg', 'Macao', 
             'Madagascar', 'Malawi', 'Malaysia', 'Maldives', 'Mali', 'Malta', 'Marshall Islands', 'Martinique', 'Mauritania', 
             'Mauritius', 'Mayotte', 'Mexico', 'Micronesia (country)', 'Moldova', 'Monaco', 'Mongolia', 'Montenegro', 
             'Montserrat', 'Morocco', 'Mozambique', 'Myanmar', 'Namibia', 'Nauru', 'Nepal', 'Netherlands', 'New Caledonia', 
             'New Zealand', 'Nicaragua', 'Niger', 'Nigeria', 'Niue', 'North America', 'North Korea', 'North Macedonia', 
             'Northern Ireland', 'Northern Mariana Islands', 'Norway', 'Oceania', 'Oman', 'Pakistan', 'Palau', 'Palestine', 
             'Panama', 'Papua New Guinea', 'Paraguay', 'Peru', 'Philippines', 'Pitcairn', 'Poland', 'Portugal', 'Puerto Rico', 
             'Qatar', 'Reunion', 'Romania', 'Russia', 'Rwanda', 'Saint Barthelemy', 'Saint Helena', 'Saint Kitts and Nevis', 
             'Saint Lucia', 'Saint Martin (French part)', 'Saint Pierre and Miquelon', 'Saint Vincent and the Grenadines', 
             'Samoa', 'San Marino', 'Sao Tome and Principe', 'Saudi Arabia', 'Scotland', 'Senegal', 'Serbia', 'Seychelles', 
             'Sierra Leone', 'Singapore', 'Sint Maarten (Dutch part)', 'Slovakia', 'Slovenia', 'Solomon Islands', 'Somalia', 
             'South Africa', 'South America', 'South Korea', 'South Sudan', 'Spain', 'Sri Lanka', 'Sudan', 'Summer Olympics 2020', 
             'Suriname', 'Sweden', 'Switzerland', 'Syria', 'Taiwan', 'Tajikistan', 'Tanzania', 'Thailand', 'Togo', 'Tokelau', 
             'Tonga', 'Transnistria', 'Trinidad and Tobago', 'Tunisia', 'Turkey', 'Turkmenistan', 'Turks and Caicos Islands', 
             'Tuvalu', 'Uganda', 'Ukraine', 'United Arab Emirates', 'United Kingdom', 'United States', 'United States Virgin Islands', 
             'Upper-middle-income countries', 'Uruguay', 'Uzbekistan', 'Vanuatu', 'Vatican', 'Venezuela', 'Vietnam', 'Wales', 
             'Wallis and Futuna', 'Western Sahara', 'Winter Olympics 2022', 'World', 'World excl. China', 'World excl. China and South Korea', 
             'World excl. China, South Korea, Japan and Singapore', 'Yemen', 'Zambia', 'Zimbabwe']

group_map = {
    'United States': 'Developed Economies - Democracies', 'United Kingdom': 'Developed Economies - Democracies',
    'Germany': 'Developed Economies - Democracies', 'Japan': 'Developed Economies - Democracies', 'Australia': 'Developed Economies - Democracies',
    'Sweden': 'Developed Economies - Democracies', 'Canada': 'Developed Economies - Democracies', 'Finland': 'Developed Economies - Democracies',
    'Netherlands': 'Developed Economies - Democracies', 'Norway': 'Developed Economies - Democracies', 'Denmark': 'Developed Economies - Democracies',
    'Iceland': 'Developed Economies - Democracies', 'Ireland': 'Developed Economies - Democracies', 'Luxembourg': 'Developed Economies - Democracies',
    'Belgium': 'Developed Economies - Democracies', 'Austria': 'Developed Economies - Democracies', 'Switzerland': 'Developed Economies - Democracies',
    
    'Brazil': 'Emerging Economies - Democracies', 'Argentina': 'Emerging Economies - Democracies', 'India': 'Emerging Economies - Democracies',
    'Mexico': 'Emerging Economies - Democracies', 'South Africa': 'Emerging Economies - Democracies', 'Indonesia': 'Emerging Economies - Democracies',
    'Colombia': 'Emerging Economies - Democracies', 'Chile': 'Emerging Economies - Democracies', 'Costa Rica': 'Emerging Economies - Democracies',
    'Philippines': 'Emerging Economies - Democracies', 'Malaysia': 'Emerging Economies - Democracies', 'Thailand': 'Emerging Economies - Democracies',
    'Portugal': 'Emerging Economies - Democracies', 'Greece': 'Emerging Economies - Democracies', 'Hungary': 'Emerging Economies - Democracies',
    'Poland': 'Emerging Economies - Democracies', 'Romania': 'Emerging Economies - Democracies',
    
    'China': 'Emerging Economies - Authoritarianism', 'Russia': 'Emerging Economies - Authoritarianism', 'Saudi Arabia': 'Emerging Economies - Authoritarianism',
    'Iran': 'Emerging Economies - Authoritarianism', 'Vietnam': 'Emerging Economies - Authoritarianism', 'Turkey': 'Emerging Economies - Authoritarianism',
    'Egypt': 'Emerging Economies - Authoritarianism', 'Belarus': 'Emerging Economies - Authoritarianism', 'Kazakhstan': 'Emerging Economies - Authoritarianism',
    'Azerbaijan': 'Emerging Economies - Authoritarianism', 'Uzbekistan': 'Emerging Economies - Authoritarianism', 'Turkmenistan': 'Emerging Economies - Authoritarianism',
    
    'Afghanistan': 'Low-Income and Fragile States', 'Haiti': 'Low-Income and Fragile States', 'Sudan': 'Low-Income and Fragile States', 
    'Democratic Republic of Congo': 'Low-Income and Fragile States', 'Mozambique': 'Low-Income and Fragile States', 'Niger': 'Low-Income and Fragile States',
    'Guinea': 'Low-Income and Fragile States', 'Guinea-Bissau': 'Low-Income and Fragile States', 'Mali': 'Low-Income and Fragile States', 
    'Chad': 'Low-Income and Fragile States', 'Burundi': 'Low-Income and Fragile States', 'Lesotho': 'Low-Income and Fragile States', 
    'Liberia': 'Low-Income and Fragile States', 'Sierra Leone': 'Low-Income and Fragile States', 'Yemen': 'Low-Income and Fragile States', 
    'Somalia': 'Low-Income and Fragile States', 'Central African Republic': 'Low-Income and Fragile States',
    
    'Germany': 'European Union (EU) and Regional Powers', 'France': 'European Union (EU) and Regional Powers', 'Italy': 'European Union (EU) and Regional Powers',
    'Spain': 'European Union (EU) and Regional Powers', 'Poland': 'European Union (EU) and Regional Powers', 'Portugal': 'European Union (EU) and Regional Powers',
    'Greece': 'European Union (EU) and Regional Powers', 'Turkey': 'European Union (EU) and Regional Powers', 'Egypt': 'European Union (EU) and Regional Powers',
    'Israel': 'European Union (EU) and Regional Powers', 'Ukraine': 'European Union (EU) and Regional Powers', 'Bulgaria': 'European Union (EU) and Regional Powers',
    'Cyprus': 'European Union (EU) and Regional Powers', 'Slovenia': 'European Union (EU) and Regional Powers', 'Slovakia': 'European Union (EU) and Regional Powers',
    'Croatia': 'European Union (EU) and Regional Powers',
}


group_df = pd.DataFrame(list(group_map.items()), columns=['country', 'Group'])

group_df.to_csv('grouped_countries.csv', index=False)

print(group_df)
#group_df.to_csv("group_country.csv", index=False)

           country                                    Group
0    United States        Developed Economies - Democracies
1   United Kingdom        Developed Economies - Democracies
2          Germany  European Union (EU) and Regional Powers
3            Japan        Developed Economies - Democracies
4        Australia        Developed Economies - Democracies
..             ...                                      ...
68        Bulgaria  European Union (EU) and Regional Powers
69          Cyprus  European Union (EU) and Regional Powers
70        Slovenia  European Union (EU) and Regional Powers
71        Slovakia  European Union (EU) and Regional Powers
72         Croatia  European Union (EU) and Regional Powers

[73 rows x 2 columns]

In [37]:
df_merge = pd.merge(df, group_df, how='inner', on='country')
df_merge

,country,date,total_cases,new_cases,new_cases_smoothed,total_cases_per_million,new_cases_per_million,new_cases_smoothed_per_million,total_deaths,new_deaths,...,population_density,median_age,life_expectancy,gdp_per_capita,extreme_poverty,diabetes_prevalence,handwashing_facilities,hospital_beds_per_thousand,human_development_index,Group
0,Afghanistan,2020-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.215546,16.752,NaN,1516.2733,NaN,10.9,48.214695,0.39,0.462,Low-Income and Fragile States
1,Afghanistan,2020-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.215546,16.752,NaN,1516.2733,NaN,10.9,48.214695,0.39,0.462,Low-Income and Fragile States
2,Afghanistan,2020-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,62.215546,16.752,NaN,1516.2733,NaN,10.9,48.214695,0.39,0.462,Low-Income and Fragile States
3,Afghanistan,2020-01-04,0.0,0.0,NaN,0.00000,0.0,NaN,0.0,0.0,...,62.215546,16.752,NaN,1516.2733,NaN,10.9,48.214695,0.39,0.462,Low-Income and Fragile States
4,Afghanistan,2020-01-05,0.0,0.0,NaN,0.00000,0.0,NaN,0.0,0.0,...,62.215546,16.752,NaN,1516.2733,NaN,10.9,48.214695,0.39,0.462,Low-Income and Fragile States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
139471,Yemen,2025-02-26,11945.0,0.0,0.0,312.50916,0.0,0.0,2159.0,0.0,...,72.395935,18.118,NaN,NaN,19.802757,5.4,48.612970,0.71,0.424,Low-Income and Fragile States
139472,Yemen,2025-02-27,11945.0,0.0,0.0,312.50916,0.0,0.0,2159.0,0.0,...,72.395935,18.118,NaN,NaN,19.802757,5.4,48.612970,0.71,0.424,Low-Income and Fragile States
139473,Yemen,2025-02-28,11945.0,0.0,0.0,312.50916,0.0,0.0,2159.0,0.0,...,72.395935,18.118,NaN,NaN,19.802757,5.4,48.612970,0.71,0.424,Low-Income and Fragile States
139474,Yemen,2025-03-01,11945.0,0.0,0.0,312.50916,0.0,0.0,2159.0,0.0,...,72.395935,18.118,NaN,NaN,19.802757,5.4,48.612970,0.71,0.424,Low-Income and Fragile States
139475,Yemen,2025-03-02,11945.0,0.0,0.0,312.50916,0.0,0.0,2159.0,0.0,...,72.395935,18.118,NaN,NaN,19.802757,5.4,48.612970,0.71,0.424,Low-Income and Fragile States

In [39]:
duplicatas = df_merge[df_merge.duplicated()]

# Exibir as duplicatas, se houver
print(f"Number of duplicates: {duplicatas.shape[0]}")

Number of duplicates: 0

In [42]:
# Definir o limite de valores NaN permitido (por exemplo, 50% de NaNs)
limite_nan = 0.3

# Remover colunas com mais de 50% de NaN
df_merged = df_merge.loc[:, df_merge.isnull().mean() < limite_nan]

# Verificar as colunas restantes ap√≥s a remo√ß√£o
print(f"Colunas restantes ap√≥s remo√ß√£o de NaNs excessivos: {df_merged.columns}")

Colunas restantes ap√≥s remo√ß√£o de NaNs excessivos: Index(['country', 'date', 'total_cases', 'new_cases', 'new_cases_smoothed',
       'total_cases_per_million', 'new_cases_per_million',
       'new_cases_smoothed_per_million', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_deaths_per_million',
       'new_deaths_per_million', 'new_deaths_smoothed_per_million', 'code',
       'continent', 'population', 'population_density', 'median_age',
       'gdp_per_capita', 'extreme_poverty', 'diabetes_prevalence',
       'hospital_beds_per_thousand', 'human_development_index', 'Group'],
      dtype='object')

In [43]:
# Verificar quantos NaNs h√° nas colunas restantes
print(f"Quantos NaNs restantes por coluna:")
print(df_merged.isnull().sum())

Quantos NaNs restantes por coluna:
country                                0
date                                   0
total_cases                         1871
new_cases                           4361
new_cases_smoothed                  4724
total_cases_per_million             1871
new_cases_per_million               4361
new_cases_smoothed_per_million      4724
total_deaths                        1871
new_deaths                          3697
new_deaths_smoothed                 4047
total_deaths_per_million            1871
new_deaths_per_million              3697
new_deaths_smoothed_per_million     4047
code                                   0
continent                              0
population                             0
population_density                     0
median_age                             0
gdp_per_capita                      1888
extreme_poverty                    11348
diabetes_prevalence                    0
hospital_beds_per_thousand         17042
human_development_index                0
Group                                  0
dtype: int64